<?php
/**
 * ProtobufNullValue
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Tokentracker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Token Tracker Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace GeminiCommerce\Tokentracker\Model;
use \GeminiCommerce\Tokentracker\ObjectSerializer;

/**
 * ProtobufNullValue Class Doc Comment
 *
 * @category Class
 * @description &#x60;NullValue&#x60; is a singleton enumeration to represent the null value for the &#x60;Value&#x60; type union.   The JSON representation for &#x60;NullValue&#x60; is JSON &#x60;null&#x60;.   - NULL_VALUE: Null value.
 * @package  GeminiCommerce\Tokentracker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProtobufNullValue
{
    /**
     * Possible values of this enum
     */
    public const NULL_VALUE = 'NULL_VALUE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NULL_VALUE
        ];
    }
}


