<?php
/**
 * TokenTrackerApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Tokentracker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Token Tracker Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@gemini-commerce.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GeminiCommerce\Tokentracker\Test\Api;

use \GeminiCommerce\Tokentracker\Configuration;
use \GeminiCommerce\Tokentracker\ApiException;
use \GeminiCommerce\Tokentracker\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TokenTrackerApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\Tokentracker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TokenTrackerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for tokenTrackerAdjustTokenBalance
     *
     * AdjustTokenBalance.
     *
     */
    public function testTokenTrackerAdjustTokenBalance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tokenTrackerGetTokenBalance
     *
     * GetTokenBalance.
     *
     */
    public function testTokenTrackerGetTokenBalance()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tokenTrackerStripeWebhook
     *
     * StripeWebhook.
     *
     */
    public function testTokenTrackerStripeWebhook()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
